#!/bin/bash

# Test NGO Notifications
# This script helps test the notification system for NGOs

BASE_URL="http://localhost:8000"

echo "=== NGO Notification Testing Guide ==="
echo ""
echo "1. Create NGO Account:"
echo "   POST $BASE_URL/auth/register"
echo "   Body: {role: 'ngo', organization_name, email, password, etc.}"
echo ""
echo "2. Approve NGO (as admin or manually in DB):"
echo "   UPDATE ngo_profiles SET verification_status='approved' WHERE id=NGO_ID;"
echo ""
echo "3. Login as NGO:"
echo "   POST $BASE_URL/auth/login"
echo "   Body: {email, password}"
echo ""
echo "4. Add NGO Location:"
echo "   POST $BASE_URL/ngo/locations"
echo "   (This triggers notification to admins)"
echo ""
echo "5. Create Donation as Donor:"
echo "   POST $BASE_URL/donations/"
echo "   Body: {ngo_location_id, meal_type, quantity_plates, etc.}"
echo "   (This triggers notification to NGO)"
echo ""
echo "6. Check Notifications:"
echo "   GET $BASE_URL/notifications/unread"
echo "   (View in bell icon on NGO dashboard)"
echo ""

# Example: Create test donation to trigger NGO notification
echo "=== Quick Test Command ==="
echo ""
echo "# 1. Login as donor"
echo "curl -X POST $BASE_URL/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"testdonor@example.com\", \"password\":\"password123\"}'"
echo ""
echo "# 2. Create donation (replace TOKEN and LOCATION_ID)"
echo "curl -X POST $BASE_URL/donations/ \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"ngo_location_id\":1, \"meal_type\":\"lunch\", \"food_type\":\"Rice\", \"quantity_plates\":50, \"donation_date\":\"2026-01-24\", \"pickup_time_start\":\"12:00\", \"pickup_time_end\":\"14:00\"}'"
echo ""
echo "# 3. Login as NGO and check notifications"
echo "curl -X GET $BASE_URL/notifications/unread \\"
echo "  -H 'Authorization: Bearer NGO_TOKEN'"
echo ""
